[workspace.package]
authors = ["The HugoByte Team <hello@hugobyte.com>"]
edition = "2021"
repository = "https://github.com/HugoByte/PoCs.git"
version = "0.0.1"

[workspace]
members = ["mpmc_channel", "mpsc_channel"]