tasks:
  - task:
      #kind filed spcifies what type of task it is.
      #(i.e for now we are focusing on openwhisk actions, future it can be any serverless functions and written in any langunage)
    kind: "OpenWhisk"
    name: "cartype"
      #for input struct to provide input for actions
    input_args:
      - name: "car_type"
        arg_type: "String"
      #for output struct to store output from actions for deserilization
    properties:
      api_host: "https://65.20.70.146:31001"
      auth_token: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
      insecure: "true"
      namespace: "guest"

  - task:
    kind: "OpenWhisk"
    name: "modelavail"
    input_args:
      - name: "car_company_list"
        arg_type: "HashMap<String,Vec<String>>"
      - name: "company_name"
        arg_type: "String"
    properties:
      api_host: "https://65.20.70.146:31001"
      auth_token: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
      insecure: "true"
      namespace: "guest"
    flow_type: Pipe
    depends_on:
      #operation defines kind of operation/opeartor needs to be applied on the task being executed
      operation: null
      task:
        - name: "cartype"
          fields:
            - car_company_list

  - task:
    kind: "OpenWhisk"
    name: "modelsprice"
    input_args:
      - name: "models"
        arg_type: "Vec<String>"
    properties:
      api_host: "https://65.20.70.146:31001"
      auth_token: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
      insecure: "true"
      namespace: "guest"

  - task:
    kind: "OpenWhisk"
    name: "purchase"
    input_args:
      - name: "model_price_list"
        arg_type: "HashMap<String,i32>"
      - name: "model_name"
        arg_type: "String"
      - name: "price"
        arg_type: "i32"
    properties:
      api_host: "https://65.20.70.146:31001"
      auth_token: "23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP"
      insecure: "true"
      namespace: "guest"

flows:
  - flow:
    #type in flow is used to mention what will be order of execution
    flow_type: "Init"
    task_name:
      "cartype"
      #to mention flow what task it is depends on
    depends_on: null

  - flow:
    flow_type: "Pipe"
    task_name: "modelavail"
    depends_on:
      #operation defines kind of operation/opeartor needs to be applied on the task being executed
      operation: null
      task:
        - name: "cartype"
          fields:
            - car_company_list
  - flow:
    flow_type: "Pipe"
    task_name: "modelsprice"
    depends_on:
      operation: null
      task:
        - name: "modelavail"
          fields:
            - models
  - flow:
    flow_type: "Term"
    task_name: "purchase"
    depends_on:
      operation: null
      task:
        - name: modelsprice
          fields:
            - model_price_list
workflow:
  name: "workflow"
  version: "0.0.1"