apiVersion: v1
kind: Service
metadata:
  name: polkadot-ocw-poc-api
  namespace: kt-<Enclave-Name>
spec:
  type: LoadBalancer
  selector:
    kurtosistech.com/id: polkadot-ocw-poc
  ports:
    - protocol: TCP
      port: 30333
      targetPort: 30333