[workspace]
resolver = "2"
members = [
    "node",
    "pallets/template",
    "pallets/template/rpc",
    "runtime",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1